version: 2.1

#####################
# ORBS
#####################
orbs:
  node: circleci/node@4.1
  heroku: circleci/heroku@1.2
  slack: circleci/slack@4.12.1

#####################
# EXECUTORS
#####################
executors:
  python_executor:
    docker:
      - image: cimg/python:3.9.16
  node_executor:
    docker:
      - image: cimg/node:18.17

#####################
# ALIASES
#####################
aliases:
  - &slack-notify-only-main
    event: pass
    branch_pattern: "main"
    template: basic_success_1
    channel: "C052YJH1LBC"
  - &slack-notify-only-main-fail
    channel: "C052YJH1LBC"
    event: fail
    template: basic_fail_1
    branch_pattern: "main"

#####################
# JOBS
#####################
jobs:
  build-frontend:
    executor: node_executor
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_modules-{{ checksum "package.json" }}
          # Install dependencies
      - run:
          name: Install Rollup for linux
          command: |
            npm i @rollup/rollup-android-arm64
      - run:
          name: Install Node.js dependencies
          command: npm install
      - save_cache:
          key: node_modules-{{ checksum "package.json" }}
          paths:
            - node_modules
      # Build the app
      - run:
          name: Build acre frontend
          command: npm run build
      - run:
          name: List dir
          command: ls -R
          # Deploy to Heroku
      - run:
          name: Deploy to Heroku
          command: |
            docker login --username=${HEROKU_USERNAME} --password=${HEROKU_API_KEY2} registry.heroku.com
            git push https://heroku:${HEROKU_API_KEY2}@git.heroku.com/acre-frontend-staging.git main --force
      - slack/notify: *slack-notify-only-main-fail
      - persist_to_workspace:
          root: ~/app
          paths:
            - .
  deploy-frontend-staging:
    executor: node_executor
    working_directory: ~/app
    parameters:
      env:
        type: enum
        enum: ["staging", "production"]
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_modules-{{ checksum "package.json" }}
      - attach_workspace:
          at: ~/app
      - run:
          name: List dir
          command: ls -R
      # Deploy to Heroku
      - run:
          name: Deploy to Heroku
          command: |
            docker login --username=${HEROKU_USERNAME} --password=${HEROKU_API_KEY2} registry.heroku.com
            git push https://heroku:${HEROKU_API_KEY2}@git.heroku.com/acre-frontend-<< parameters.env >>.git main --force
      - slack/notify: *slack-notify-only-main-fail

  deploy-notifier:
    executor: node_executor
    working_directory: ~/app
    steps:
      - slack/notify: *slack-notify-only-main

#####################
# WORKFLOWS
#####################
workflows:
  acre-frontend:
    jobs:
      - build-frontend:
          context:
            - heroku
            - slack
      - deploy-notifier:
          requires:
            - build-frontend
          context:
            - heroku
            - slack
      # - slack/on-hold:
      #     channel: C052YJH1LBC
      #     context: slack
      #     requires:
      #       - build-frontend
      # - deploy-fe-staging-approval:
      #     name: approve-staging-deploy
      #     type: approval
      #     filters:
      #       branches:
      #         only:
      #           - main
      #     requires:
      #       - slack/on-hold
      # - deploy-frontend-staging:
      #     matrix:
      #       parameters:
      #         env: ["staging"]
      #     context:
      #       - heroku
      #       - slack
      #     requires:
      #       - build-frontend
