# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  node: circleci/node@4.1
  heroku: circleci/heroku@1.2
  slack: circleci/slack@4.12.1

aliases:
  - &slack-notify-only-main
      event: pass
      branch_pattern: "master"
      template: basic_success_1
      channel: "C052YJH1LBC"


jobs:
  build:
    docker:
      - image:  cimg/node:18.17 
    working_directory: ~/app

    steps:
      - checkout
      # Install dependencies
      - run:
          name: Install Node.js dependencies
          command: npm install

      # Build the app
      - run:
          name: Build the app
          command: npm run build

  deploy:
    docker:
      - image: circleci/python:3.8 # Use Python or any other base image for deploying to Heroku
    working_directory: ~/app
    parameters:
      env:
        type: enum
        enum: ["staging", "production"]
    steps:
      - checkout

      # Deploy to Heroku
      - run:
          name: Deploy to Heroku
          command: |
            docker login --username=${HEROKU_USERNAME} --password=${HEROKU_API_KEY2} registry.heroku.com
            git push https://heroku:${HEROKU_API_KEY2}@git.heroku.com/acre-frontend-<< parameters.env >>.git main
      - slack/notify: *slack-notify-only-main

workflows:
  deploy-fe-staging:
    jobs:
      - build
      - deploy:
          matrix:
            parameters:
              env: ["staging"]
          context:
            - heroku
            - slack
          requires:
            - build
